- hosts: all
  vars:
          - ip: "{{ ansible_default_ipv4.address }}"
  tasks:
          - name: Download hadoop software
            copy:
                    src: "/root/hadoop-1.2.1-1.x86_64.rpm"
                    dest: "/root"
     
          - name: "Download jdk"
            copy:
                    src: "/root/jdk-8u171-linux-x64.rpm"
                    dest: "/root"
          - name: "Install jdk and hadoop"
            command: "sudo rpm -ivh jdk-8u171-linux-x64.rpm hadoop-1.2.1-1.x86_64.rpm --force"

          - name: "Configure core-site.xml"
            template:
                    src: "/etc/hadoop/core-site.xml"
                    dest: "/etc/hadoop/core-site.xml"

- hosts: namenode
  vars:
          - name: "name"
          - folder: "/root/namenode"
  tasks:
          - name: "Creates directory"
            file:
                    path: "{{ folder }}"
                    state: directory

          - name: "Configure hdfs-site.xml"
            template:
                    src: "/etc/hadoop/hdfs-site.xml"
                    dest: "/etc/hadoop/hdfs-site.xml"
          - name: format name node
            shell: "echo Y|hadoop namenode -format"
       
          - name: start namenode
            command: hadoop-daemon.sh start namenode


- hosts: datanode
  vars:
          - name: "data"
          - folder: "/root/dn1"
  tasks:
          - name: Creates directory
            file:
                    path: "{{ folder }}"
                    state: directory


          - name: "Configure hdfs-site.xml"
            template:
                    src: "/etc/hadoop/hdfs-site.xml"
                    dest: "/etc/hadoop/hdfs-site.xml"

          - name: "Start datanode"
            command: hadoop-daemon.sh start datanode





